#!/usr/bin/env node
"use strict";

const fs=require("node:fs");
const path=require("node:path");
const crypto=require("node:crypto");
const cp=require("node:child_process");
const {PACKAGE_NAME,VERSION,FEATURES,PLUGINS,PROVIDERS}=require("./package-spec");
const {sharedFiles,featureFiles,hostFiles,providerFiles}=require("./runtime-templates");
const {algorithmFiles}=require("./plugin-algorithms-template");

const repoRoot=path.resolve(__dirname,"..");
const outRoot=path.join(repoRoot,"dist",PACKAGE_NAME);
fs.rmSync(path.join(repoRoot,"dist"),{recursive:true,force:true});
fs.mkdirSync(outRoot,{recursive:true});
const written=new Map();
function write(rel,content){if(written.has(rel))throw new Error("Duplicate path: "+rel);const abs=path.join(outRoot,rel);fs.mkdirSync(path.dirname(abs),{recursive:true});const text=String(content).replace(/\r\n/g,"\n");fs.writeFileSync(abs,text,"utf8");written.set(rel,text);}
function json(rel,obj){write(rel,JSON.stringify(obj,null,2)+"\n");}
function sha(data){return crypto.createHash("sha256").update(data).digest("hex");}
function jsString(x){return JSON.stringify(x);}

const rootPackage={name:"wahoogpt-harici-40-eklenti-32-ozellik",version:VERSION,description:"WahooGPT için bağımsız, ücretsiz ve local-first 40 eklenti + 32 çekirdek özellik paketi",license:"MIT",main:"src/host/plugin-host.js",bin:{"wahoo-plugins":"bin/wahoo-plugins.js"},scripts:{doctor:"node scripts/doctor.js",test:"node scripts/run-tests.js","verify:manifests":"node scripts/verify-manifests.js","verify:permissions":"node scripts/verify-permissions.js","checksums":"node scripts/create-checksums.js"},engines:{node:">=20"}};
json("package.json",rootPackage);
write("LICENSE",`MIT License\n\nCopyright (c) 2026 WahooGPT\n\nPermission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the \"Software\"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software.\n\nTHE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND.\n`);
json("BUILD_INFO.json",{package:PACKAGE_NAME,version:VERSION,generatedAt:new Date().toISOString(),node:process.version,plugins:PLUGINS.length,features:FEATURES.length,providers:PROVIDERS.length,generatorCommit:process.env.GITHUB_SHA||null});

for(const [p,c] of Object.entries({...sharedFiles(),...algorithmFiles(),...featureFiles(),...hostFiles(),...providerFiles()}))write(p,c);

function schemaFor(plugin){
  const common={type:"object",additionalProperties:true};
  const byId={
    "repository-map":{type:"object",required:["root"],properties:{root:{type:"string"},maxFiles:{type:"number"}}},
    "context-builder":{type:"object",required:["root","task"],properties:{root:{type:"string"},task:{type:"string"},activeFiles:{type:"array",items:{type:"string"}},dirtyFiles:{type:"array",items:{type:"string"}},tokenBudget:{type:"number"}}},
    "local-search":{type:"object",required:["root","query"],properties:{root:{type:"string"},query:{type:"string"},regex:{type:"boolean"},maxResults:{type:"number"}}},
    "workspace-doctor":{type:"object",required:["root"],properties:{root:{type:"string"}}},
    "architecture-graph":{type:"object",required:["root"],properties:{root:{type:"string"},maxFiles:{type:"number"}}},
    "duplicate-code-finder":{type:"object",required:["root"],properties:{root:{type:"string"},minLines:{type:"number"},threshold:{type:"number"}}},
    "workspace-indexer":{type:"object",required:["root"],properties:{root:{type:"string"},generation:{type:"number"},latestGeneration:{type:"number"},previous:{type:"object"}}},
    "prompt-library":{type:"object",required:["action"],properties:{action:{type:"string",enum:["list","add","remove","export","import"]},file:{type:"string"},title:{type:"string"},body:{type:"string"},tags:{type:"array",items:{type:"string"}}}},
    "migration-planner":{type:"object",required:["before","after"],properties:{before:{type:"object"},after:{type:"object"},engine:{type:"string"}}},
    "patch-safety-validator":{type:"object",required:["diff"],properties:{diff:{type:"string"},expectedBaseHash:{type:"string"},actualBaseHash:{type:"string"}}}
  };
  return byId[plugin.id]||common;
}
function outputSchema(plugin){return{type:"object",description:plugin.description,additionalProperties:true};}
function engineSource(id){return`"use strict";\nconst algorithms=require("../../shared/plugin-algorithms");\nasync function run(input={},ctx={}){const fn=algorithms[${jsString(id)}];if(typeof fn!=="function")throw new Error("Algorithm bulunamadı: ${id}");return fn(input,ctx);}\nmodule.exports={run};\n`;}
function indexSource(){return`"use strict";\nconst engine=require("./engine");const {ok,fromError}=require("../../shared/result-envelope");const {validate}=require("../../shared/schema-validator");const inputSchema=require("./input.schema.json");\nasync function run(input,ctx){const errors=validate(inputSchema,input);if(errors.length)return{ok:false,error:{code:"E_SCHEMA",message:"Girdi şeması geçersiz",details:{errors},retryable:false}};try{return ok(await engine.run(input,ctx));}catch(e){return fromError(e);}}\nmodule.exports={run};\n`;}
function readme(plugin){return`# ${plugin.name}\n\n${plugin.description}\n\n## Kategori\n\n\`${plugin.category}\`\n\n## İzinler\n\n${plugin.permissions.length?plugin.permissions.map(x=>`- \`${x}\``).join("\n"):"- İzin gerektirmez."}\n\n## Güvenlik\n\n- Workspace dışına çıkmaz.\n- Çıktıda secret değeri döndürmez.\n- Dosya değişikliği gerekiyorsa checkpoint ve onay katmanı üzerinden çalışır.\n- Otomatik commit veya patch uygulaması yapmaz.\n\n## Kullanım\n\n\`\`\`bat\nnode bin/wahoo-plugins.js run ${plugin.id} --json input.json\n\`\`\`\n\n## Sözleşme\n\nGirdi ve çıktı şemaları yan dosyalardadır. Hatalar standart ResultEnvelope olarak döner.\n`;}

function smokeSpec(id){
 const simple={input:{},assert:"assert.equal(result.ok,true); assert.equal(typeof result.data,'object');"};
 const map={
  "repository-map":{fixture:true,inputExpr:"{root:fixture}",assert:"assert.equal(result.ok,true); assert.ok(result.data.fileCount>=2); assert.ok(result.data.byLanguage.JavaScript>=1);"},
  "context-builder":{fixture:true,inputExpr:"{root:fixture,task:'alpha hatası',activeFiles:['src/alpha.js'],tokenBudget:1000}",assert:"assert.equal(result.ok,true); assert.ok(result.data.picked.some(x=>x.path==='src/alpha.js'));"},
  "code-review":{file:true,inputExpr:"{files:[sampleFile]}",sample:"eval('1+1');\nconst w={webPreferences:{nodeIntegration:true}};",assert:"assert.equal(result.ok,true); assert.ok(result.data.findings.some(x=>x.rule==='eval')); assert.ok(result.data.findings.some(x=>x.rule==='node-integration'));"},
  "test-generator":{file:true,inputExpr:"{files:[sampleFile]}",sample:"export function add(a,b){return a+b}\nmodule.exports.sub=(a,b)=>a-b;",assert:"assert.equal(result.ok,true); assert.ok(result.data.results[0].symbols.includes('add'));"},
  "bug-fix-planner":{input:{stack:"ENOENT: no such file",exitCode:1},assert:"assert.equal(result.ok,true); assert.ok(result.data.rootCauses.some(x=>/dosya yolu/.test(x.cause)));"},
  "dependency-auditor":{fixture:true,extra:"fs.writeFileSync(path.join(fixture,'package.json'),JSON.stringify({dependencies:{foo:'latest'}})); fs.writeFileSync(path.join(fixture,'package-lock.json'),'{}');",inputExpr:"{root:fixture}",assert:"assert.equal(result.ok,true); assert.ok(result.data.issues.some(x=>x.code==='UNPINNED'));"},
  "documentation-generator":{fixture:true,extra:"fs.writeFileSync(path.join(fixture,'package.json'),JSON.stringify({name:'demo',scripts:{test:'node --test'}}));",inputExpr:"{root:fixture}",assert:"assert.equal(result.ok,true); assert.match(result.data.markdown,/Kurulum/);"},
  "changelog-builder":{input:{commits:[{message:"feat: yeni"},{message:"fix: hata"}]},assert:"assert.equal(result.ok,true); assert.equal(result.data.groups.Added.length,1); assert.equal(result.data.groups.Fixed.length,1);"},
  "commit-message-assistant":{input:{diff:"docs/README.md",subject:"dokümanı güncelle"},assert:"assert.equal(result.ok,true); assert.match(result.data.message,/^docs:/);"},
  "file-summarizer":{file:true,inputExpr:"{files:[sampleFile]}",sample:"// TODO: düzelt\nexports.foo=function foo(){};",assert:"assert.equal(result.ok,true); assert.equal(result.data.results[0].todos.length,1);"},
  "local-search":{fixture:true,inputExpr:"{root:fixture,query:'needle'}",extra:"fs.writeFileSync(path.join(fixture,'find.txt'),'hay needle burada');",assert:"assert.equal(result.ok,true); assert.equal(result.data.matches.length,1);"},
  "diff-explainer":{input:{diff:"+++ b/a.js\n+element.innerHTML=x"},assert:"assert.equal(result.ok,true); assert.equal(result.data.security,true);"},
  "log-analyzer":{input:{lines:["2026-01-01T10:00:00Z ERROR pid=12 C:/app/main.js failed port:3000","2026-01-02T10:00:00Z ERROR pid=99 C:/app/main.js failed port:4000"]},assert:"assert.equal(result.ok,true); assert.equal(result.data.clusters[0].count,2);"},
  "api-contract-review":{input:{schema:{type:"object",required:["x"],properties:{}}},assert:"assert.equal(result.ok,true); assert.ok(result.data.issues.some(x=>x.code==='REQUIRED_MISSING'));"},
  "secret-scanner":{file:true,inputExpr:"{files:[sampleFile]}",sample:"OPENAI_API_KEY=sk-abcdefghijklmnopqrstuvwxyz12345",assert:"assert.equal(result.ok,true); assert.ok(result.data.findings.length>=1); assert.equal(JSON.stringify(result.data).includes('abcdefghijklmnopqrstuvwxyz12345'),false);"},
  "refactor-planner":{input:{target:"main.js"},assert:"assert.equal(result.ok,true); assert.equal(result.data.steps.length,7);"},
  "workspace-doctor":{fixture:true,inputExpr:"{root:fixture}",extra:"fs.writeFileSync(path.join(fixture,'package.json'),JSON.stringify({scripts:{test:'node --test'},devDependencies:{electron:'1.0.0'}})); fs.writeFileSync(path.join(fixture,'package-lock.json'),'{}');",assert:"assert.equal(result.ok,true); assert.ok(result.data.checks.some(x=>x.id==='electron'&&x.ok));"},
  "architecture-graph":{fixture:true,inputExpr:"{root:fixture}",extra:"fs.writeFileSync(path.join(fixture,'src','beta.js'),'module.exports=1');",assert:"assert.equal(result.ok,true); assert.ok(result.data.nodes.length>=2);"},
  "duplicate-code-finder":{fixture:true,inputExpr:"{root:fixture,minLines:2,threshold:0.5}",extra:"fs.writeFileSync(path.join(fixture,'src','beta.js'),'function a(){\n const value=1;\n return value;\n}\n'); fs.writeFileSync(path.join(fixture,'src','gamma.js'),'function b(){\n const value=1;\n return value;\n}\n');",assert:"assert.equal(result.ok,true); assert.ok(result.data.matches.length>=1);"},
  "migration-planner":{input:{before:{a:{type:"string"}},after:{b:{type:"number"}}},assert:"assert.equal(result.ok,true); assert.ok(result.data.warnings.some(x=>x.code==='DATA_LOSS'));"},
  "build-log-diagnoser":{input:{text:"npm warn deprecated x\nBuild finished",exitCode:0},assert:"assert.equal(result.ok,true); assert.equal(result.data.success,true); assert.equal(result.data.warningCount,1);"},
  "encoding-mojibake-doctor":{file:true,inputExpr:"{files:[sampleFile]}",sample:"HÄ±zlÄ± AraÃ§lar",assert:"assert.equal(result.ok,true); assert.ok(result.data.findings.some(x=>x.code==='MOJIBAKE'));"},
  "environment-key-doctor":{input:{env:{GEMINI_API_KEYY:"hidden"}},assert:"assert.equal(result.ok,true); assert.equal(result.data.typos[0].target,'GEMINI_API_KEY'); assert.equal(JSON.stringify(result.data).includes('hidden'),false);"},
  "release-readiness":{input:{gates:[{id:"tests",ok:true},{id:"secret",ok:false}]},assert:"assert.equal(result.ok,true); assert.equal(result.data.ready,false);"},
  "flaky-test-analyzer":{input:{runs:[{tests:[{name:"x",ok:true,durationMs:10}]},{tests:[{name:"x",ok:false,durationMs:20,message:"EADDRINUSE"}]}]},assert:"assert.equal(result.ok,true); assert.ok(result.data.findings.some(x=>x.code==='NONDETERMINISTIC_RESULT'));"},
  "localization-integrity":{input:{locales:{tr:{hello:"Merhaba {{name}}"},en:{hello:"Hello"}}},assert:"assert.equal(result.ok,true); assert.ok(result.data.findings.some(x=>x.code==='PLACEHOLDER_MISMATCH'));"},
  "workspace-indexer":{fixture:true,inputExpr:"{root:fixture,generation:1,latestGeneration:1}",assert:"assert.equal(result.ok,true); assert.equal(result.data.stale,false); assert.ok(result.data.manifest.files['src/alpha.js']);"},
  "dependency-upgrade-planner":{input:{current:"1.0.0",target:"2.0.0",nativeElectron:true},assert:"assert.equal(result.ok,true); assert.ok(result.data.risks.some(x=>x.code==='MAJOR'));"},
  "patch-safety-validator":{input:{diff:"--- a/.env\n+++ b/.env\n+OPENAI_API_KEY=sk-abcdefghijklmnopqrstuvwxyz12345"},assert:"assert.equal(result.ok,true); assert.equal(result.data.applyReady,false); assert.ok(result.data.findings.some(x=>x.code==='SECRET_ADDED'));"}
 };
 return map[id]||simple;
}

for(const plugin of PLUGINS){
 const base=`src/plugins/${plugin.id}`;
 json(`${base}/manifest.json`,{id:plugin.id,name:plugin.name,version:VERSION,hostApi:"2.0.0",category:plugin.category,description:plugin.description,entry:"index.js",permissions:plugin.permissions,inputSchema:"input.schema.json",outputSchema:"output.schema.json",localFirst:true,networkRequired:false,limits:{timeoutMs:60000,maxOutputBytes:5_000_000}});
 json(`${base}/input.schema.json`,schemaFor(plugin));
 json(`${base}/output.schema.json`,outputSchema(plugin));
 write(`${base}/index.js`,indexSource());write(`${base}/engine.js`,engineSource(plugin.id));write(`${base}/README.md`,readme(plugin));
 const s=smokeSpec(plugin.id);const fixtureSetup=s.fixture?`const fixture=fs.mkdtempSync(path.join(os.tmpdir(),${jsString(plugin.id+"-")}));fs.mkdirSync(path.join(fixture,"src"),{recursive:true});fs.writeFileSync(path.join(fixture,"src","alpha.js"),"const beta=require('./beta');\\nmodule.exports={beta};\\n");${s.extra||""}`:"";const fileSetup=s.file?`const sampleFile=path.join(os.tmpdir(),${jsString(plugin.id+"-")}+Date.now()+".txt");fs.writeFileSync(sampleFile,${jsString(s.sample||"sample")});`:"";const input=s.inputExpr||JSON.stringify(s.input||{});
 write(`${base}/tests/plugin.test.js`,`"use strict";\nconst test=require("node:test");const assert=require("node:assert/strict");const fs=require("node:fs");const os=require("node:os");const path=require("node:path");const plugin=require("../index");\ntest(${jsString(plugin.id+" gerçek davranış")},async()=>{${fixtureSetup}${fileSetup}const result=await plugin.run(${input},{});${s.assert}});\ntest(${jsString(plugin.id+" şema ve hata zarfı")},async()=>{const result=await plugin.run(null,{});assert.equal(typeof result.ok,"boolean");if(!result.ok)assert.ok(result.error.code);});\n`);
}

const cli=`#!/usr/bin/env node\n"use strict";const fs=require("node:fs"),path=require("node:path");const {Host}=require("../src/host/plugin-host");async function main(){const[a,id,...rest]=process.argv.slice(2);const host=new Host(path.join(__dirname,"..","src","plugins"));host.discover();if(a==="list"){console.log(host.discover().join("\\n"));return;}if(a!=="run"||!id)throw new Error("Kullanım: wahoo-plugins run <id> --json <file|json>");const j=rest.indexOf("--json"),raw=j>=0?rest[j+1]:"{}";let input={};try{input=JSON.parse(fs.existsSync(raw)?fs.readFileSync(raw,"utf8"):raw);}catch(e){throw new Error("JSON okunamadı: "+e.message);}const r=await host.run(id,input,{});console.log(JSON.stringify(r,null,2));process.exitCode=r.ok?0:1;}main().catch(e=>{console.error(e.message);process.exit(1);});\n`;
write("bin/wahoo-plugins.js",cli);

write("integration/preload-contract.example.js",`"use strict";\nconst {contextBridge,ipcRenderer}=require("electron");contextBridge.exposeInMainWorld("wahooPlugins",{list:()=>ipcRenderer.invoke("plugins:list"),run:input=>ipcRenderer.invoke("plugins:run",input),cancel:runId=>ipcRenderer.invoke("plugins:cancel",{runId}),onEvent:cb=>{const h=(_e,p)=>cb(p);ipcRenderer.on("plugins:event",h);return()=>ipcRenderer.removeListener("plugins:event",h);}});\n`);
write("integration/ipc-handlers.example.js",`"use strict";\nfunction register({ipcMain,host,validateSender}){ipcMain.handle("plugins:list",e=>{validateSender(e);return host.plugins?Array.from(host.plugins.keys()):[];});ipcMain.handle("plugins:run",async(e,input)=>{validateSender(e);if(!input||typeof input.id!=="string")throw new Error("id");return host.run(input.id,input.payload||{},input.context||{});});}\nmodule.exports={register};\n`);
write("integration/canvas-adapter.example.js",`"use strict";\nfunction toCanvas(result){if(!result.ok)return{tab:"Hata",severity:"error",content:result.error};return{tab:"Bulgular",severity:"info",content:result.data,meta:result.meta};}\nmodule.exports={toCanvas};\n`);
json("integration/plugin-menu-registry.example.json",PLUGINS.map(p=>({id:p.id,label:p.name,category:p.category})));
json("integration/tool-policy.example.json",{"workspace.read":"allow","workspace.write":"ask","process.run":"ask","network":"ask","*":"deny"});
write("integration/WAHOOGPT_V18_ENTEGRASYON_REHBERI.md",`# WahooGPT V18 Entegrasyon Rehberi\n\nBu paket ana kaynak ZIP'e karıştırılmaz. Önerilen konum: \`%APPDATA%\\WahooGPT\\extensions\\wahoo-free-pack-v2\`.\n\n1. Paketi ayrı klasöre çıkarın.\n2. \`npm test\` ve \`npm run doctor\` çalıştırın.\n3. Electron main process içinde PluginHost oluşturun.\n4. Preload için yalnız dar, isimlendirilmiş API kullanın; generic invoke vermeyin.\n5. Write/process/network izinlerini Tool Policy + Approval Gate üzerinden geçirin.\n6. Canvas panelinde ResultEnvelope ve Evidence kayıtlarını gösterin.\n7. Renderer'a API anahtarı, raw fs veya child_process göndermeyin.\n`);

const catalog=PLUGINS.map((p,i)=>`## ${i+1}. ${p.name}\n\n- ID: \`${p.id}\`\n- Kategori: \`${p.category}\`\n- İzinler: ${p.permissions.join(", ")||"yok"}\n- Davranış: ${p.description}\n`).join("\n");
write("docs/40_EKLENTI_KATALOGU.md",`# 40 Eklenti Kataloğu\n\n${catalog}`);
write("docs/32_CEKIRDEK_OZELLIK.md",`# 32 Çekirdek Özellik\n\n${FEATURES.map((x,i)=>`${i+1}. **${x}** — güvenli, test edilebilir ve provider bağımsız çalışma zamanı modülü.`).join("\n")}\n`);
write("docs/V2_HATA_DUZELTME_RAPORU.md",`# V2 Hata Düzeltme Raporu\n\n- Prefix tabanlı path kontrolü canonical realpath + path.relative ile değiştirildi.\n- Permission Boundary artık raw fs/child_process vermiyor.\n- Atomik yazma base hash, same-directory temp, fsync, backup ve indeterminate ayrımı kullanıyor.\n- Replay runId bazlı; terminal sonrası orphan olaylar ayrılıyor.\n- Regex aramasında lastIndex sıfırlanıyor ve ReDoS sınırı var.\n- Secret scanner duplicate sk-* sınıflandırmasını generic anahtar olarak tekilleştiriyor.\n- Workspace Doctor hardcoded başarısızlık yerine gerçek paket/dosya/CSP taraması yapıyor.\n- Provider timeout'u external signal ile birlikte çalışıyor; health check varsayılan olarak ücretli çağrı yapmıyor.\n- DeepSeek V4 varsayılanı ve legacy model uyarısı eklendi.\n- Gemini Interactions primary, generateContent fallback olarak ayrıldı.\n`);
write("docs/PROVIDER_2026_UYUMLULUK.md",`# Provider 2026 Uyumluluk\n\n## OpenAI\nResponses API birincildir. Özel OpenAI-compatible sunucular için chat/completions fallback ayrı seçenektir.\n\n## Gemini\nInteractions API birincildir ve privacy için store=false kullanılır; generateContent fallback'tir. Anahtar x-goog-api-key header'ındadır.\n\n## Anthropic\nMessages API, system ve content block/tool_use çıktılarını normalize eder.\n\n## DeepSeek\nVarsayılan deepseek-v4-flash; deepseek-v4-pro desteklenir. Legacy adlar uyarı verir.\n\n## Kimi/Moonshot\nKIMI/MOONSHOT env alias'ları ve ayarlanabilir base/model kullanılır.\n\n## Yerel\nVarsayılan yalnız localhost; uzak HTTP açık opt-in ister.\n`);
write("docs/GUVENLIK_MODELI.md",`# Güvenlik Modeli\n\n- Least privilege capability API\n- Canonical workspace path sınırı\n- Symlink/reparse escape engeli\n- Atomik file mutation + checkpoint\n- Argv-only process spawn ve allowlist\n- Secret redaction tüm log/evidence/provider hatalarında\n- Network ve write işlemlerinde approval gate\n- Renderer'a raw Node yetkisi verilmez\n`);
write("docs/HATA_KODLARI.md",`# Hata Kodları\n\nE_INPUT, E_SCHEMA, E_PATH, E_SYMLINK, E_PERMISSION, E_APPROVAL, E_TIMEOUT, E_CANCELED, E_NETWORK, E_AUTH, E_RATE_LIMIT, E_UPSTREAM, E_CONFLICT, E_CORRUPT, E_OUTPUT_LIMIT, E_INDETERMINATE, E_UNSUPPORTED, E_UNKNOWN.\n`);
write("docs/FAULT_INJECTION_MATRISI.md",`# Fault Injection Matrisi\n\n| Senaryo | Beklenen |\n|---|---|\n| Symlink workspace dışına | E_SYMLINK |\n| Base hash değişti | E_CONFLICT |\n| Replace sonrası restore başarısız | E_INDETERMINATE |\n| Provider 429 | E_RATE_LIMIT + Retry-After |\n| Provider malformed JSON | E_SCHEMA |\n| Yanıt max bytes aşıldı | E_OUTPUT_LIMIT |\n| Process timeout | killed=true |\n| Stream terminal sonrası delta | reddedilir |\n| Corrupt JSONL tail | sağlam satırlara kadar recovery |\n`);
write("docs/TEST_MATRISI.md",`# Test Matrisi\n\n- 40 plugin gerçek davranış + schema/error envelope\n- 32 feature count/load\n- Permission/path traversal/symlink\n- Provider mock 401/429/5xx/malformed/oversized/timeout\n- Windows path case/UNC lexical kontroller\n- Secret redaction regression\n- ZIP kaynak bütünlüğü ve checksum\n`);
write("docs/KNOWN_LIMITATIONS.md",`# Bilinen Sınırlar\n\n- Statik analiz reflection ve runtime-generated kodu kesin sınıflandıramaz.\n- Provider çağrıları kullanıcının anahtarı, kotası ve fiyatlandırmasına tabidir.\n- Lisans raporu hukuki tavsiye değildir.\n- Windows process-tree davranışı Windows üzerinde ayrıca smoke test edilmelidir.\n- Paket patch uygulamaz; Patch Safety Validator yalnız doğrular.\n`);
write("docs/DERIN_ARASTIRMA_RAPORU.md",`# Derin Araştırma Uygulama Özeti\n\nPaket; modern coding-agent ürünlerinde görülen repository context, tool policy, approval, checkpoint, replay, provider routing, structured output, file search ve evidence ilkelerini kapalı kaynak kod kopyalamadan bağımsız olarak uygular. Local-first analizler API gerektirmez. Bulut model adaptörleri kullanıcı anahtarıyla çalışır.\n`);

write("README.md",`# WahooGPT Harici 40 Eklenti + 32 Özellik V2\n\nBağımsız, ücretsiz ve local-first Node.js kaynak paketidir. Ana WahooGPT V18 ZIP'ine gömülü değildir.\n\n## Gereksinim\n- Node.js 20 veya 22\n- Windows 10/11, Linux veya macOS\n\n## Doğrulama\n\n\`\`\`bat\nnpm test\nnpm run doctor\nnpm run verify:manifests\nnpm run verify:permissions\n\`\`\`\n\n## CLI\n\n\`\`\`bat\nnode bin\\wahoo-plugins.js list\nnode bin\\wahoo-plugins.js run repository-map --json input.json\n\`\`\`\n\n## WahooGPT V18\n\nBkz. \`integration/WAHOOGPT_V18_ENTEGRASYON_REHBERI.md\`.\n\n## Ücret ve API\nYerel analiz eklentileri ücretsizdir. OpenAI, Gemini, Anthropic, DeepSeek ve Kimi çağrıları kullanıcının kendi hesabı/kotasıyla çalışır.\n`);

write("tests/core.test.js",`"use strict";const test=require("node:test"),assert=require("node:assert/strict");const {transition}=require("../src/features/task-state-machine");const {allocate}=require("../src/features/context-budgeter");const {replay}=require("../src/features/run-replay");test("state terminalden çıkmaz",()=>assert.throws(()=>transition("completed","running")));test("budget total aşmaz",()=>{const r=allocate(1000,[{id:"a",requested:900,priority:1}],{minResponse:300});assert.ok(r.used<=1000);assert.ok(r.allocation.response>=300);});test("replay run bazlıdır",()=>{const r=replay([{runId:"a",sequence:0,type:"delta"},{runId:"b",sequence:1,type:"completed"}]);assert.deepEqual(r.runs.b.gaps,[0]);});\n`);
write("tests/plugins.test.js",`"use strict";const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path");const root=path.join(__dirname,"..","src","plugins");test("40 plugin ve 7 dosya",()=>{const dirs=fs.readdirSync(root).filter(x=>fs.statSync(path.join(root,x)).isDirectory());assert.equal(dirs.length,40);for(const d of dirs)for(const p of["manifest.json","input.schema.json","output.schema.json","index.js","engine.js","README.md","tests/plugin.test.js"])assert.ok(fs.existsSync(path.join(root,d,p)),d+":"+p);});\n`);
write("tests/permissions.test.js",`"use strict";const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),os=require("node:os"),path=require("node:path");const {capabilities}=require("../src/features/permission-boundary");test("write izinsiz reddedilir",async()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),"perm-")),c=capabilities({root,permissions:["workspace.read"]});await assert.rejects(()=>c.writeText("x.txt","x"),/denied/);});test("path traversal reddedilir",async()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),"path-")),c=capabilities({root,permissions:["workspace.read"]});await assert.rejects(()=>c.readText("../outside"));});\n`);
write("tests/provider-contracts.test.js",`"use strict";const test=require("node:test"),assert=require("node:assert/strict");test("providerlar config health ile ücretli çağrı yapmaz",async()=>{for(const id of["openai","gemini","anthropic","deepseek","kimi","local-openai-compatible"]){const p=require("../src/providers/"+id);let called=false;const r=await p.healthCheck({fetchImpl:async()=>{called=true;}});assert.equal(called,false);assert.equal(r.mode,"config");}});test("OpenAI malformed JSON güvenli hata",async()=>{process.env.OPENAI_API_KEY="test";const p=require("../src/providers/openai");const r=await p.completion({messages:[],fetchImpl:async()=>({ok:true,status:200,headers:{get:()=>"application/json"},text:async()=>"{"})});assert.equal(r.ok,false);assert.equal(r.error.code,"E_SCHEMA");delete process.env.OPENAI_API_KEY;});\n`);
write("tests/fault-injection.test.js",`"use strict";const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),os=require("node:os"),path=require("node:path");const {write}=require("../src/features/atomic-file-writer");test("stale base hash engellenir",async()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),"atomic-"));fs.writeFileSync(path.join(root,"a.txt"),"old");await assert.rejects(()=>write(root,"a.txt","new",{expectedHash:"bad"}));});const {create}=require("../src/features/stream-normalizer");test("terminal sonrası delta engellenir",()=>{const s=create("r");s.complete({});assert.throws(()=>s.delta("late"));});\n`);
write("tests/windows-paths.test.js",`"use strict";const test=require("node:test"),assert=require("node:assert/strict"),path=require("node:path");const {inside}=require("../src/shared/workspace-path");test("prefix benzer klasör içeride sayılmaz",()=>{const root=path.resolve("C:/work/app"),bad=path.resolve("C:/work/application");assert.equal(inside(root,bad),false);});\n`);
write("tests/security-regressions.test.js",`"use strict";const test=require("node:test"),assert=require("node:assert/strict");const {redact,scanSecrets}=require("../src/shared/secret-redaction");test("secret değeri çıktıdan silinir",()=>{const s="OPENAI_API_KEY=sk-abcdefghijklmnopqrstuvwxyz12345",r=redact(s);assert.equal(r.text.includes("abcdefghijklmnopqrstuvwxyz12345"),false);assert.ok(r.findings.length);});test("aynı sk anahtarı tek finding",()=>assert.equal(scanSecrets("sk-abcdefghijklmnopqrstuvwxyz12345").length,1));\n`);
write("tests/zip-integrity.test.js",`"use strict";const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path");test("kaynak ağacı minimum sayıları",()=>{const root=path.join(__dirname,"..");const walk=d=>fs.readdirSync(d,{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(path.join(d,e.name)):[path.join(d,e.name)]);const files=walk(root);assert.ok(files.length>=370,files.length);assert.equal(files.filter(x=>x.endsWith("manifest.json")&&x.includes(path.sep+"plugins"+path.sep)).length,40);assert.equal(files.filter(x=>x.includes(path.sep+"features"+path.sep)&&x.endsWith(".js")).length,32);});\n`);

write("scripts/run-tests.js",`#!/usr/bin/env node\n"use strict";const fs=require("node:fs"),path=require("node:path"),cp=require("node:child_process");function walk(d){return fs.readdirSync(d,{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(path.join(d,e.name)):[path.join(d,e.name)]);}const root=path.join(__dirname,"..");const tests=walk(root).filter(x=>x.endsWith(".test.js")&&!x.includes("node_modules"));const r=cp.spawnSync(process.execPath,["--test",...tests],{stdio:"inherit"});process.exit(r.status??1);\n`);
write("scripts/verify-manifests.js",`#!/usr/bin/env node\n"use strict";const fs=require("node:fs"),path=require("node:path"),assert=require("node:assert/strict");const root=path.join(__dirname,"..","src","plugins"),dirs=fs.readdirSync(root);assert.equal(dirs.length,40);for(const d of dirs){const m=JSON.parse(fs.readFileSync(path.join(root,d,"manifest.json"),"utf8"));assert.equal(m.id,d);assert.ok(fs.existsSync(path.join(root,d,m.entry)));assert.ok(Array.isArray(m.permissions));}console.log("40 manifest doğrulandı");\n`);
write("scripts/verify-permissions.js",`#!/usr/bin/env node\n"use strict";const fs=require("node:fs"),path=require("node:path"),assert=require("node:assert/strict");const allowed=new Set(["workspace.read","workspace.write","process.run","network"]),root=path.join(__dirname,"..","src","plugins");for(const d of fs.readdirSync(root)){const m=require(path.join(root,d,"manifest.json"));for(const p of m.permissions)assert.ok(allowed.has(p),d+":"+p);}console.log("İzinler doğrulandı");\n`);
write("scripts/create-checksums.js",`#!/usr/bin/env node\n"use strict";const fs=require("node:fs"),path=require("node:path"),crypto=require("node:crypto");const root=path.join(__dirname,"..");function walk(d){return fs.readdirSync(d,{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(path.join(d,e.name)):[path.join(d,e.name)]);}const out={};for(const f of walk(root).filter(x=>!x.endsWith("SOURCE_SHA256SUMS.json"))){const rel=path.relative(root,f).replace(/\\\\/g,"/");out[rel]=crypto.createHash("sha256").update(fs.readFileSync(f)).digest("hex");}fs.writeFileSync(path.join(root,"SOURCE_SHA256SUMS.json"),JSON.stringify(out,null,2)+"\\n");console.log(Object.keys(out).length+" checksum");\n`);
write("scripts/doctor.js",`#!/usr/bin/env node\n"use strict";const fs=require("node:fs"),path=require("node:path"),assert=require("node:assert/strict");const root=path.join(__dirname,"..");function walk(d){return fs.readdirSync(d,{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(path.join(d,e.name)):[path.join(d,e.name)]);}const files=walk(root),rel=files.map(f=>path.relative(root,f).replace(/\\\\/g,"/"));assert.equal(new Set(rel).size,rel.length,"duplicate path");assert.ok(files.length>=370,"dosya sayısı "+files.length);for(const f of files){const b=fs.readFileSync(f);assert.ok(b.length>0,"empty "+f);const s=b.toString("utf8");assert.equal(s.includes("�"),false,"replacement char "+f);assert.equal(/TODO_PLACEHOLDER|REMOVE_THIS|fake success/i.test(s),false,"placeholder "+f);if(f.endsWith(".json"))JSON.parse(s);}assert.equal(rel.filter(x=>/^src\\/plugins\\/[^/]+\\/manifest.json$/.test(x)).length,40);assert.equal(rel.filter(x=>/^src\\/features\\/[^/]+\\.js$/.test(x)).length,32);console.log(JSON.stringify({ok:true,files:files.length,plugins:40,features:32,providers:6},null,2));\n`);

cp.execFileSync(process.execPath,[path.join(outRoot,"scripts","create-checksums.js")],{stdio:"inherit"});
const checksums=JSON.parse(fs.readFileSync(path.join(outRoot,"SOURCE_SHA256SUMS.json"),"utf8"));write("PACKAGE_CONTENT_SHA256.txt",sha(Object.entries(checksums).sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>k+":"+v).join("\n"))+"  "+PACKAGE_NAME+" source-tree\n");

function validate(){const files=[...written.keys(),"SOURCE_SHA256SUMS.json"],errors=[];const count=p=>files.filter(p).length;if(PLUGINS.length!==40)errors.push("plugin spec");if(FEATURES.length!==32)errors.push("feature spec");if(PROVIDERS.length!==6)errors.push("provider spec");if(count(x=>/^src\/plugins\/[^/]+\/manifest\.json$/.test(x))!==40)errors.push("manifest count");if(count(x=>/^src\/plugins\/[^/]+\/engine\.js$/.test(x))!==40)errors.push("engine count");if(count(x=>/^src\/plugins\/[^/]+\/tests\/plugin\.test\.js$/.test(x))!==40)errors.push("plugin test count");if(count(x=>/^src\/features\/[^/]+\.js$/.test(x))!==32)errors.push("feature count");if(files.length<370)errors.push("file count "+files.length);for(const p of written.keys())if(/TODO_PLACEHOLDER|REMOVE_THIS|fake success/i.test(written.get(p)))errors.push("placeholder "+p);return{ok:errors.length===0,errors,totalFiles:files.length,plugins:40,features:32,providers:6,docs:count(x=>x.startsWith("docs/")),tests:count(x=>x.endsWith(".test.js"))};}
const report=validate();json("VALIDATION_REPORT.json",report);if(!report.ok)throw new Error(JSON.stringify(report));
console.log(JSON.stringify(report,null,2));
